version: "3.8"

services:
  app:
    container_name: react-docker-dev
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    environment:
      aaa: ${AAA}
    command: "tail -f /dev/null"
    